spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    cache: false
    encoding: utf-8
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: java.text.SimpleDateFormat
#mybatis-plus:
#    configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#      use-actual-param-name: true
#  global-config:
#    db-config:
#      id-type: auto
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-actual-param-name: true
#  mapper-locations: classpath*:mapper/**/*Mapper.xml